# Make truth table for 'and', 'or' and 'not'

print("Truth Table for 'and'")
print("-"*20)
print("True  | True  |", True and True)
print("True  | False |", True and False)
print("False | True  |", False and True)
print("False | False |", False and False)
print("-"*20)
print("="*20)

print("Truth Table for 'or'")
print("-"*20)
print("True  | True  |", True or True)
print("True  | False |", True or False)
print("False | True  |", False or True)
print("False | False |", False or False)
print("-"*20)
print("="*20)

print("Truth Table for 'no'")
print("-"*20)
print("True  |", not True)
print("False |", not False)
print("-"*20)
print("="*20)
