# Write a program to input eight numbers from the user and display all the unique numbers (once)

s = set()
print("Enter 8 numbers: ")
s.add(int(input()))
s.add(int(input()))
s.add(int(input()))
s.add(int(input()))
s.add(int(input()))
s.add(int(input()))
s.add(int(input()))
s.add(int(input()))
print(s)